### ISSUE TITLE
Deleting posts from blog

### ISSUE THREAD

**Issue by Konstantinusz** [orjanv/early-galaxy#1]
Great tool, works flawlessly. Any chance for implementing post removing from blog? Post editing / updating would be also a valuable feature.

**Comment by orjanv** [comment]
Hi @Konstantinusz, I hadn't planned to implement that as my use would only require posting. But as you say, it will be valuable functionality, if not for me, but someone else. I might look into this later, but feel free to begin yourself. :)

**Comment by Konstantinusz** [comment]
Unfortunately I have nearly zero knowledge of Python, as I learnt only Ruby, and every simple modification would be a hard demand for me. I barely succeed to implement passing the blog ID as a command line parameter with -i, because I have multiple blogs and multiple accounts. Currently I simply overwrite from my calling Ruby script the JSON file containing the credentials at every posting occasion.

**Comment by orjanv** [comment]
I see @Konstantinusz, I'll let you know if I implement this.

**Comment by Konstantinusz** [comment]
Okay, and please, could you point me where I can read the documentation (if exists) of those Python libraries you use in your EarlyGalaxy program (google-api-python-client). I plan to learn some Python language because maybe I could use it to script renaming youtube videos, adding subtitles to youtube videos, and adding youtube videos to youtube-playlists and similar tasks.

**Comment by orjanv** [comment]
I guess this is a good place to start: https://github.com/google/google-api-python-client/
