### ISSUE TITLE
Labels aren't posted to the blog

### ISSUE THREAD

**Issue by Konstantinusz** [orjanv/early-galaxy#2]
Hi! 
Using your script I realized, that labels (or tags) aren't posted with option --labels , -l
But I found out that only a minor change in the code is needed:
```
# Assign argument values to variables
    flags = parent.parse_args(argv[1:])
    blogtitle = flags.title
    blogtags = flags.labels.split(",")
    blogfilename = flags.src
    blog_id = flags.blogid
```

labels need to be splitted into a list with .split(",")

**Comment by orjanv** [comment]
Awesome, thanks. 
https://github.com/orjanv/early-galaxy/commit/ca32df1e579deeba453455124a35b1b1d8606cd8
