### ISSUE TITLE
There is an error message: ModuleNotFoundError: No module named 'oauth2client'

### ISSUE THREAD

**Issue by Konstantinusz** [orjanv/early-galaxy#3]
It worked till now, but today says:
```
from oauth2client import client
ModuleNotFoundError: No module named 'oauth2client'
```

**Comment by orjanv** [comment]
Thanks, will look at it :)

**Comment by orjanv** [comment]
Hi, sorry for the late response, but have you made sure you have installed oauth2client with, for example $ sudo pip install oauth2client ?

**Comment by orjanv** [comment]
closing.
